/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital;

/**
 *
 * @author OMER
 */
public class AddPatient extends javax.swing.JFrame {

    /**
     * Creates new form AddPatient
     */
    public AddPatient() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        PatientNameLbl = new javax.swing.JLabel();
        PatientNameTxt = new javax.swing.JTextField();
        PatientSurnameLbl = new javax.swing.JLabel();
        PatientSurnameTxt = new javax.swing.JTextField();
        PatientDiseaseLbl = new javax.swing.JLabel();
        PatientDiseaseCmbx = new javax.swing.JComboBox<>();
        Doctor3RdBtx = new javax.swing.JRadioButton();
        Doctor2RdBtx = new javax.swing.JRadioButton();
        Doctor1RdBtx = new javax.swing.JRadioButton();
        DoctorNameLbl = new javax.swing.JLabel();
        BackToMainBtx = new javax.swing.JButton();
        AddPatientBtx = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PatientNameLbl.setText("Patient Name");

        PatientSurnameLbl.setText("Patient Surname");

        PatientDiseaseLbl.setText("Patient Disease");

        PatientDiseaseCmbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hastalık Yok", "Şeker", "Kalp", "Romatizma" }));

        buttonGroup1.add(Doctor3RdBtx);
        Doctor3RdBtx.setText("Hale Kaya");

        buttonGroup1.add(Doctor2RdBtx);
        Doctor2RdBtx.setText("Ayşe Günay");

        buttonGroup1.add(Doctor1RdBtx);
        Doctor1RdBtx.setText("Hakan Gündüz");

        DoctorNameLbl.setText("Doctor Name");

        BackToMainBtx.setText("Back To Main Menu");
        BackToMainBtx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToMainBtxActionPerformed(evt);
            }
        });

        AddPatientBtx.setText("Add Patient");
        AddPatientBtx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPatientBtxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(PatientDiseaseCmbx, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PatientDiseaseLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PatientNameLbl)
                                    .addComponent(PatientNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PatientSurnameLbl)
                                    .addComponent(PatientSurnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Doctor1RdBtx)
                                        .addGap(18, 18, 18)
                                        .addComponent(Doctor2RdBtx)))
                                .addGap(35, 35, 35)
                                .addComponent(Doctor3RdBtx))
                            .addComponent(DoctorNameLbl))
                        .addContainerGap(85, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(AddPatientBtx)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BackToMainBtx)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PatientNameLbl)
                .addGap(18, 18, 18)
                .addComponent(PatientNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PatientSurnameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PatientSurnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PatientDiseaseLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PatientDiseaseCmbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(DoctorNameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Doctor1RdBtx)
                    .addComponent(Doctor2RdBtx)
                    .addComponent(Doctor3RdBtx))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackToMainBtx)
                    .addComponent(AddPatientBtx))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackToMainBtxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToMainBtxActionPerformed
        // TODO add your handling code here:
        Entrance e = new Entrance();
        e.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackToMainBtxActionPerformed

    private void clearFrame()
    {
        this.PatientDiseaseCmbx.setSelectedIndex(0);
        this.PatientNameTxt.setText("");
        this.PatientSurnameTxt.setText("");
        this.buttonGroup1.clearSelection();
    }
    private void AddPatientBtxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPatientBtxActionPerformed
        // TODO add your handling code here:
        String name = PatientNameTxt.getText().toString();
        String surname = PatientSurnameTxt.getText().toString();
        String disease = PatientDiseaseCmbx.getSelectedItem().toString();
        String doctorName = " ";
        
        if(Doctor1RdBtx.isSelected())
        {
            doctorName = Doctor1RdBtx.getText().toString();
        }
        else if(Doctor2RdBtx.isSelected())
        {
            doctorName = Doctor2RdBtx.getText().toString();
        }
        else if(Doctor3RdBtx.isSelected())
        {
            doctorName = Doctor3RdBtx.getText().toString();
        }
        
        Patient p = new Patient(name, surname, disease, doctorName);
        PatientOperator.addPatient(p);
        
        clearFrame();
              
    }//GEN-LAST:event_AddPatientBtxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPatientBtx;
    private javax.swing.JButton BackToMainBtx;
    private javax.swing.JRadioButton Doctor1RdBtx;
    private javax.swing.JRadioButton Doctor2RdBtx;
    private javax.swing.JRadioButton Doctor3RdBtx;
    private javax.swing.JLabel DoctorNameLbl;
    private javax.swing.JComboBox<String> PatientDiseaseCmbx;
    private javax.swing.JLabel PatientDiseaseLbl;
    private javax.swing.JLabel PatientNameLbl;
    private javax.swing.JTextField PatientNameTxt;
    private javax.swing.JLabel PatientSurnameLbl;
    private javax.swing.JTextField PatientSurnameTxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    // End of variables declaration//GEN-END:variables
}
